In [76]:
import pandas as pd

df = pd.read_csv("시도별_평균초혼연령_20260525003556.csv", header=[0, 1])
df.head()

     시도별   1990          1991          1992          1993          1994  ...  \
     시도별     남편     아내     남편     아내     남편     아내     남편     아내     남편  ...
0     전국  27.79  24.78  27.91  24.84  28.01  24.93  28.09  25.01  28.21  ...
1  서울특별시  28.26  25.54  28.38  25.58  28.47  25.63  28.52  25.71  28.62  ...
2  부산광역시  27.96  25.03  28.07  25.08  28.19  25.23  28.25  25.30  28.38  ...
3  대구광역시  27.66  24.95  27.78  25.03  27.93  25.11  28.01  25.16  28.07  ...
4  인천광역시  27.80  24.95  27.90  25.03  28.01  24.98  28.17  25.12  28.23  ...

    2021          2022          2023          2024          2025
      남편     아내     남편     아내     남편     아내     남편     아내     남편     아내
0  33.35  31.08  33.72  31.26  33.97  31.45  33.86  31.55  33.85  31.62
1  33.85  31.91  34.17  32.15  34.38  32.42  34.32  32.44  34.18  32.40
2  33.40  31.30  33.94  31.67  34.31  31.95  34.16  32.04  34.00  31.99
3  33.32  31.03  33.63  31.22  33.71  31.43  33.74  31.54  33.77  31.61
4  33.21  30.95  33.63  31.29  33.79  31.57  33.74  31.67  33.93  31.82

[5 rows x 73 columns]

In [77]:
# 컬럼 레벨 이름 지정
df.columns.names = ["연도", "성별"]

df.head()

연도    시도별   1990          1991          1992          1993          1994  ...  \
성별    시도별     남편     아내     남편     아내     남편     아내     남편     아내     남편  ...
0      전국  27.79  24.78  27.91  24.84  28.01  24.93  28.09  25.01  28.21  ...
1   서울특별시  28.26  25.54  28.38  25.58  28.47  25.63  28.52  25.71  28.62  ...
2   부산광역시  27.96  25.03  28.07  25.08  28.19  25.23  28.25  25.30  28.38  ...
3   대구광역시  27.66  24.95  27.78  25.03  27.93  25.11  28.01  25.16  28.07  ...
4   인천광역시  27.80  24.95  27.90  25.03  28.01  24.98  28.17  25.12  28.23  ...

연도   2021          2022          2023          2024          2025
성별     남편     아내     남편     아내     남편     아내     남편     아내     남편     아내
0   33.35  31.08  33.72  31.26  33.97  31.45  33.86  31.55  33.85  31.62
1   33.85  31.91  34.17  32.15  34.38  32.42  34.32  32.44  34.18  32.40
2   33.40  31.30  33.94  31.67  34.31  31.95  34.16  32.04  34.00  31.99
3   33.32  31.03  33.63  31.22  33.71  31.43  33.74  31.54  33.77  31.61
4   33.21  30.95  33.63  31.29  33.79  31.57  33.74  31.67  33.93  31.82

[5 rows x 73 columns]

In [ ]:
# 첫 번째 컬럼은 ('시도별', '시도별') 같은 형태이므로 따로 잡아둠
id_col = df.columns[0]

result = (
    df
    .set_index(id_col)
    .rename_axis(index="시도별")
    .stack(level="연도", future_stack=True)
    .reset_index()      # stack()을 한 뒤에는 "시도별"과 "연도"가 인덱스에 들어가있음 -> 다시 일반 컬럼으로 꺼냄........ stack() 직후에는 인덱스가 두 개짜리 MultiIndex가 됨 -> reset_index를 하면 시도별과 연도를 둘 다 일반 컬럼으로 꺼냄
    .rename(columns={
        "남편": "평균초혼연령(남편)",
        "아내": "평균초혼연령(아내)"
    })
)

# 컬럼명 위에 남는 name 제거
result.columns.name = None

result

    시도별    연도 평균초혼연령(남편) 평균초혼연령(아내)
0    전국  1990      27.79      24.78
1    전국  1991      27.91      24.84
2    전국  1992      28.01      24.93
3    전국  1993      28.09      25.01
4    전국  1994      28.21      25.14
..   ..   ...        ...        ...
679  국외  2021      32.77      29.63
680  국외  2022      33.03      28.74
681  국외  2023      33.53      28.38
682  국외  2024      33.56      28.57
683  국외  2025      33.41      28.47

[684 rows x 4 columns]